[32mINFO    [0m Login Test:test_login.py:22 Executing TC_2 with locked_out_user as username and secret_sauce as password in cloud browser...
[32mINFO    [0m Login Test:test_login.py:25 Starting browser session...
[32mINFO    [0m Login Test:test_login.py:30 Entering login credentials...
[32mINFO    [0m Login Test:test_login.py:36 Validating login...
[31m[1mERROR   [0m Login Test:test_login.py:41 Epic sadface: Sorry, this user has been locked out.
[32mINFO    [0m Login Test:test_login.py:44 Actual result matches the expected condition